### ISSUE TITLE
Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

### ISSUE THREAD

**Issue by kexul** [collabora/WhisperSpeech#65]
Hi, I got the following error when run the example colab: 
```
RuntimeError                              Traceback (most recent call last)

[<ipython-input-7-8f3d1d1ad737>](https://localhost:8080/#) in <cell line: 3>()
      1 # this is very slow right now since our inference code is not very optimized
      2 # but even without this crucial optimization it is still better than real-time on an RTX 4090
----> 3 pipe.generate_to_notebook("""
      4 This is the first demo of Whisper Speech, a fully open source text-to-speech model trained by Collabora and Lion on the Juwels supercomputer.
      5 """)

4 frames

[/usr/local/lib/python3.10/dist-packages/whisperspeech/s2a_delar_mup_wds_mlang.py](https://localhost:8080/#) in <listcomp>(.0)
    514         if show_progress_bar: it = progress_bar(it)
    515         with record_function("encode"):
--> 516             stoks, speakers = [x.repeat(bs, 1) for x in (stoks, speakers)]
    517             xenc, xenc_positions, _ = self.run_encoder(stoks, speakers)
    518             toks_positions = torch.arange(N, device=dev)

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor
```

**Comment by jpc** [comment]
Hey, sorry about that. I pushed a new version today that solves this issue.

**Comment by Melona-BS** [comment]
![image](https://github.com/collabora/WhisperSpeech/assets/70928779/5bcab950-2051-4f1e-8201-c339d83b5f0a)

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-44-de81f3a88132>](https://localhost:8080/#) in <cell line: 3>()
      1 # We can also mix different languages (e.g. for borrowed words) in a single sentence
      2 stoks = pipe.t2s.generate(["To jest pierwszy test wielojęzycznego ", " Whisper Speech ", ", modelu zamieniającego tekst na mowę, który Collabora i Laion nauczyli na superkomputerze", " Jewels."], lang=['pl', 'en', 'pl', 'en'])
----> 3 pipe.vocoder.decode_to_notebook(pipe.s2a.generate(stoks, pipe.default_speaker.unsqueeze(0)))

2 frames
[/usr/local/lib/python3.10/dist-packages/whisperspeech/s2a_delar_mup_wds_mlang.py](https://localhost:8080/#) in <listcomp>(.0)
    493         if show_progress_bar: it = progress_bar(it)
    494         with record_function("encode"):
--> 495             stoks = stoks.unsqueeze(1)
    496             speakers = speakers.unsqueeze(1)
    497             stoks, speakers = [x.repeat(bs, 1) for x in (stoks, speakers)]

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor
```
This error still occurs.

**Comment by jpc** [comment]
Good point, thanks. I forgot to update the examples in the notebook.

It should be fixed now but if you have a notebook with local changes the fix is to add `[0]` after: `stoks` like this:
```python
pipe.vocoder.decode_to_notebook(pipe.s2a.generate(stoks[0], pipe.default_speaker.unsqueeze(0)))
```
